Fix: wget on centos fails to download from github; switch to curl
Concrete error message is

ERROR: certificate common name `www.github.com' doesn't match requested host name `raw.github.com'.